version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: event_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: event_management
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - event_network

  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: event_backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./backend/storage:/var/www/storage
    depends_on:
      - mysql
    networks:
      - event_network
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=event_management
      - DB_USERNAME=root
      - DB_PASSWORD=password

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: event_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - event_network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: event_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - nginx
    networks:
      - event_network

volumes:
  mysql_data:
    driver: local

networks:
  event_network:
    driver: bridge